---
- name: Configure RADIUS on MikroTik CHR
  hosts: mikrotik
  gather_facts: no
  collections:
    - community.routeros
  tasks:
    - name: Add RADIUS client
      routeros_command:
        commands:
          - /radius add service=hotspot address=35.227.71.209 secret=testing123
